In [1]:
import numpy as np


In [8]:
def softmax(vals):
    exps = np.exp(X - max(X))
    softs = exps / np.sum(exps)

In [95]:
y_val = np.array([1,4,0,2,3])
arr  = np.random.randn(3,5)
vals = np.max(arr,axis=1)
exps = np.exp(arr.T - vals)
sums  = np.sum(exps,axis=1)
nrml = np.divide(exps.T,sums).T
logs = np.log(np.max(nrml,axis=0))
print(arr[0])
print(vals[0])
print(exps.T[0])
print(nrml.T[0])
print(np.sum(nrml[0]))
print(np.max(nrml,axis=0))
print(-logs)

[-0.21798743  0.9165464  -0.06446919 -0.25333841 -0.0257991 ]
0.9165463962180775
[0.32157199 1.         0.37493013 0.3104027  0.38971269]
[0.30589088 0.5620884  0.24234035 0.18593558 0.26156896]
1.0
[0.5620884  0.64636136 0.59901407]
[0.57609615 0.43639654 0.5124702 ]


In [94]:
sum([0.99761376, 0.99701684 ,0.99753324, 0.99634498 ,0.99586836, 0.99723335,
 0.99729482, 0.99784725 ,0.9982115,  0.99791552])

9.972879619999999

In [96]:
np.arange(3.0)

array([0., 1., 2.])

In [97]:
k = np.random.randn(4,5)

In [117]:
print(k)
np.expand_dims(np.argmax(k,axis=1),axis=1)

[[ 1.44257381 -0.32342283 -1.48228297  0.35923394  2.0234265 ]
 [-0.01587491 -0.16713283 -1.52023518 -0.19259175 -1.35606604]
 [ 1.20796039 -0.22300958 -0.86948341 -0.0803711  -1.68593726]
 [ 0.71527122  2.13445569 -0.73988036  1.25085819 -1.69847284]]


array([[4],
       [0],
       [0],
       [1]], dtype=int64)